# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab35637b417280f53c3a0978819f741a0998091818ed300d290e0a4eb4d9480c55c0111266fb71281a31c4121804113e3e6ff02706d61e84f0722fab7d8e085

test:
  secret_key_base: 94c6f503f64d6b78799814c6dafc37762db8b059bd16ba36c12f0dae502323cf73c5372a06586e13601bbc1323e668b4e1516526f9c8461adfbf6705887f6f97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
